dataset_dump_path: 
  raw: data/raw/
  interim: data/interim/
  processed: data/processed/
target_col: loan_status
int64_columns:
- person_age
- person_income
- loan_amnt
# - loan_status
- cb_person_cred_hist_length
float_columns:
- person_emp_length
- loan_int_rate
- loan_percent_income
object_columns:
- person_home_ownership
- loan_intent
- loan_grade
- cb_person_default_on_file
value_person_home_ownership:
- "RENT"
- "OWN"
- "MORTGAGE"
- "OTHER"
value_loan_intent:
- "PERSONAL"
- "EDUCATION"
- "MEDICAL"
- "VENTURE"
- "HOMEIMPROVEMENT"
- "DEBTCONSOLIDATION"
value_loan_grade:
- "A"
- "B"
- "C"
- "D"
- "E"
- "F"
- "G"
value_cb_person_default_on_file:
- "Y"
- "N"
label_encoder_columns:
- loan_grade
ohe_columns:
- person_home_ownership
- loan_intent
- cb_person_default_on_file
feature_num_columns:
- person_age
- person_income
- loan_amnt
- cb_person_cred_hist_length
- person_emp_length
- loan_int_rate
- loan_percent_income
model_dump_path: models/
features:
- person_age
- person_income
- loan_amnt
- cb_person_cred_hist_length
- person_emp_length
- loan_int_rate
- loan_percent_income
- person_home_ownership
- loan_intent
- loan_grade
- cb_person_default_on_file